language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base
    - source /opt/qt58/bin/qt58-env.sh

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ../hotspot
  - make -j4
  - sudo apt-get -y install checkinstall
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - cp ./usr/share/applications/*.desktop .
  - cp ./usr/share/icons/hicolor/256x256/apps/*.png .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/hotspot -bundle-non-qt-libs
  # Workaround for https://github.com/probonopd/linuxdeployqt/issues/83
  - ./linuxdeployqt*.AppImage --appimage-extract
  - ./squashfs-root/usr/bin/patchelf --set-rpath '$ORIGIN/../..' ./appdir/usr/lib/hotspot/libexec/*
  # Apparently the qt_prfxpath in libQt5Core.so
  # is not relative to libQt5Core.so but to the binary that is being executed, is this clever?
  - ( cd ./appdir/usr/lib/hotspot/ ;  ln -s ../../plugins/ . )
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/hotspot -appimage 
  - curl --upload-file ./Hotspot-*.AppImage https://transfer.sh/Hotspot-git.$(git rev-parse --short HEAD)-x86_64.AppImage
