language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt59base qt59x11extras elfutils libelf-dev libdw-dev libasm-dev
    - source /opt/qt*/bin/qt*-env.sh
    - git clone git://anongit.kde.org/extra-cmake-modules
    - cd extra-cmake-modules
    - mkdir build
    - cd build
    - cmake .. # or run : cmake -DCMAKE_INSTALL_PREFIX=/usr .. &&
    - make
    - sudo make install
    - cd ../..
    - # Precompiled KF5
    - wget -c "https://github.com/chigraph/precompiled-kf5-linux/releases/download/precompiled/kf5-gcc6-linux64-release.tar.xz"
    - tar xf kf5-gcc6-linux64-release.tar.xz
    - sudo cp -Rf root/kf5-release/* /opt/qt*/

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir install ; find appdir/
  - cp ./usr/share/applications/*.desktop .
  - cp ./usr/share/icons/hicolor/256x256/apps/*.png .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - find appdir/
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  # Workaround for https://github.com/probonopd/linuxdeployqt/issues/83 - no longer needed?
  # - ./linuxdeployqt*.AppImage --appimage-extract
  # - ./squashfs-root/usr/bin/patchelf --set-rpath '$ORIGIN/../..' ./appdir/usr/lib/hotspot/libexec/*
  # Apparently the qt_prfxpath in libQt5Core.so
  # is not relative to libQt5Core.so but to the binary that is being executed, is this clever?
  # - ( cd ./appdir/usr/lib/hotspot/ ;  ln -s ../../plugins/ . )
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage 
  - curl --upload-file ./Hotspot-*.AppImage https://transfer.sh/Hotspot-git.$(git rev-parse --short HEAD)-x86_64.AppImage
